# Generated by Django 3.1.2 on 2020-10-16 15:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Principal')),
                ('interest_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('frequency', models.CharField(choices=[('ANNUALLY-1', 'Annually'), ('SEMI-ANNUALLY-2', 'Semi-Annually'), ('QUARTERLY-4', 'Quarterly'), ('BI-MONTHLY-6', 'Bi-Monthly'), ('MONTHLY-12', 'Monthly'), ('BI-WEEKLY-24', 'Bi-Weekly')], default='MONTHLY-12', max_length=15, verbose_name='Frequency of Payment')),
                ('ip_address', models.GenericIPAddressField(protocol='IPV4', verbose_name='IP Address')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('bank', models.CharField(max_length=50, verbose_name='Bank')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['request_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Payment Value')),
                ('loan_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_loan', to='api.loan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
