# Generated by Django 3.1.2 on 2020-10-19 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor inicial do empréstimo')),
                ('taxa_juros', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Juros (%)')),
                ('periodo', models.IntegerField(verbose_name='Período (Número de Meses)')),
                ('endereco_ip', models.GenericIPAddressField(protocol='IPV4', verbose_name='Endereço IP do cliente')),
                ('data_solicitacao_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data que o empréstimo foi solicitado')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['data_solicitacao_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Pagamento')),
                ('emprestimo_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimo_pagamento', to='api.emprestimo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
