# Generated by Django 3.1.2 on 2020-10-17 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='periodo',
            field=models.IntegerField(verbose_name='Período (Número de Meses)'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='taxa_juros',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Juros (%)'),
        ),
    ]
