# Generated by Django 3.1.2 on 2020-10-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201017_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='valor_parcela',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao_emprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data que o empréstimo foi solicitado'),
        ),
    ]
